name: instabug_flutter_task
description: A new Flutter project that fetch movies list from native side and beck with the results to flutter side
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shimmer: ^2.0.0
  flutter_riverpod: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

  #This is the package that we are going to use to generate the code
  pigeon: ^9.0.5
  mockito: ^5.3.2


flutter:
  uses-material-design: true
