// Autogenerated from Pigeon (v9.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class Movie;

@interface Movie : NSObject
+ (instancetype)makeWithTitle:(nullable NSString *)title
    date:(nullable NSString *)date;
@property(nonatomic, copy, nullable) NSString * title;
@property(nonatomic, copy, nullable) NSString * date;
@end

/// The codec used by MoviesApi.
NSObject<FlutterMessageCodec> *MoviesApiGetCodec(void);

@protocol MoviesApi
/// @return `nil` only when `error != nil`.
- (nullable NSArray<Movie *> *)getMoviesPageNumber:(NSNumber *)pageNumber error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void MoviesApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MoviesApi> *_Nullable api);

NS_ASSUME_NONNULL_END
