// Autogenerated from Pigeon (v9.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface Movie ()
+ (Movie *)fromList:(NSArray *)list;
+ (nullable Movie *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation Movie
+ (instancetype)makeWithTitle:(nullable NSString *)title
    date:(nullable NSString *)date {
  Movie* pigeonResult = [[Movie alloc] init];
  pigeonResult.title = title;
  pigeonResult.date = date;
  return pigeonResult;
}
+ (Movie *)fromList:(NSArray *)list {
  Movie *pigeonResult = [[Movie alloc] init];
  pigeonResult.title = GetNullableObjectAtIndex(list, 0);
  pigeonResult.date = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable Movie *)nullableFromList:(NSArray *)list {
  return (list) ? [Movie fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.title ?: [NSNull null]),
    (self.date ?: [NSNull null]),
  ];
}
@end

@interface MoviesApiCodecReader : FlutterStandardReader
@end
@implementation MoviesApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [Movie fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface MoviesApiCodecWriter : FlutterStandardWriter
@end
@implementation MoviesApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[Movie class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface MoviesApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation MoviesApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[MoviesApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[MoviesApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *MoviesApiGetCodec() {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    MoviesApiCodecReaderWriter *readerWriter = [[MoviesApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void MoviesApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MoviesApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.MoviesApi.getMovies"
        binaryMessenger:binaryMessenger
        codec:MoviesApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getMoviesPageNumber:completion:)], @"MoviesApi api (%@) doesn't respond to @selector(getMoviesPageNumber:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_pageNumber = GetNullableObjectAtIndex(args, 0);
        [api getMoviesPageNumber:arg_pageNumber completion:^(NSArray<Movie *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
