// Autogenerated from Pigeon (v9.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class Movie;

@interface Movie : NSObject
+ (instancetype)makeWithTitle:(nullable NSString *)title
    date:(nullable NSString *)date;
@property(nonatomic, copy, nullable) NSString * title;
@property(nonatomic, copy, nullable) NSString * date;
@end

/// The codec used by BookApi.
NSObject<FlutterMessageCodec> *BookApiGetCodec(void);

@protocol BookApi
- (void)moviesPageNumber:(NSNumber *)pageNumber completion:(void (^)(NSArray<Movie *> *_Nullable, FlutterError *_Nullable))completion;
@end

extern void BookApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BookApi> *_Nullable api);

NS_ASSUME_NONNULL_END
